python google-blocked.py butterfinger 0
python google-blocked.py butterfinger 1
python google-blocked.py butterfinger 2
python google-blocked.py butterfinger 3
taskkill /F /IM chrome.exe
python google-blocked.py butterfinger 4
python google-blocked.py butterfinger 5
python google-blocked.py butterfinger 6
python google-blocked.py butterfinger 7
taskkill /F /IM chrome.exe
python google-blocked.py butterfinger 8
python google-blocked.py butterfinger 9
python google-blocked.py butterfinger 10
python google-blocked.py butterfinger 11
python google-blocked.py butterfinger 12
taskkill /F /IM chrome.exe
python google-blocked.py butterfinger 13
python google-blocked.py butterfinger 14
python google-blocked.py butterfinger 15
python google-blocked.py butterfinger 16
taskkill /F /IM chrome.exe
python google-blocked.py butterfinger 17
python google-blocked.py butterfinger 18
python google-blocked.py butterfinger 19
python google-blocked.py butterfinger 20
taskkill /F /IM chrome.exe
python google-blocked.py butterfinger 21
python google-blocked.py butterfinger 22
python google-blocked.py butterfinger 23
python google-blocked.py butterfinger 24
taskkill /F /IM chrome.exe
python google-blocked.py butterfinger 25
python google-blocked.py butterfinger 26
python google-blocked.py butterfinger 27
python google-blocked.py butterfinger 28
taskkill /F /IM chrome.exe
python google-blocked.py butterfinger 29
python google-blocked.py butterfinger 30